"""skillforge.lock: pinned upstream commits, per-skill provenance, output digests."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from skillforge.errors import ConfigError

LOCK_NAME = "skillforge.lock"


@dataclass
class Lock:
    version: int = 1
    sources: dict[str, dict[str, str]] = field(default_factory=dict)
    skills: dict[str, dict[str, str]] = field(default_factory=dict)
    outputs: dict[str, str] = field(default_factory=dict)

    def commit_for(self, alias: str) -> str | None:
        return (self.sources.get(alias) or {}).get("commit")


def load(root: Path) -> Lock:
    path = root / LOCK_NAME
    if not path.is_file():
        return Lock()
    data: Any = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        raise ConfigError(f"{path}: must be a mapping")
    if data.get("version", 1) != 1:
        raise ConfigError(f"{path}: unsupported lock version {data.get('version')!r}")
    return Lock(
        sources=data.get("sources") or {},
        skills=data.get("skills") or {},
        outputs=data.get("outputs") or {},
    )


def dump(lock: Lock, root: Path) -> None:
    payload = {
        "version": lock.version,
        "sources": dict(sorted(lock.sources.items())),
        "skills": dict(sorted(lock.skills.items())),
        "outputs": dict(sorted(lock.outputs.items())),
    }
    text = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False, width=10_000)
    header = (
        "# Generated by skillforge. Do not edit by hand.\n# Regenerate with `skillforge build`.\n"
    )
    (root / LOCK_NAME).write_text(header + text, encoding="utf-8")
